config/routes.rb
Rails.application.routes.draw do
  resources :graduates
  root to: "pages#home"

  devise_for :classmates, prefix: 'my'

  resources :classmates

  get "/admin_dashboard", to: 'pages#admin_dashboard', as: "admin_dashboard"
  get "/admin_classmates", to: 'classmates#admin_index', as: "admin_classmates"
  get "/events/:event_id/admin_rsvps", to: 'rsvps#admin_index', as: "admin_rsvps"
  get "/events/:event_id/admin_attendees", to: 'attendees#admin_index', as: "admin_attendees"

  post "/images", to: "images#create", as: "new_image"

  post "/hook", to: 'rsvps#hook'

  resources :events do
    resources :rsvps do
      resources :attendees
    end
    resources :event_options
  end

  resources :posts

end

app/models/attendee.rb
class Attendee < ApplicationRecord

  belongs_to :rsvp
  belongs_to :event_option


  validates :name, presence: true
  validates :event_option_id, presence: true
  #validates :rsvp_id, presence:true

  delegate :price, to: :event_option

end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]

  def index
    @attendees = Attendee.all
  end

  def admin_index
    @event = Event.find(params[:event_id])
    @attendees = Attendee.joins(:rsvp).where(rsvps: {event_id: @event.id})
  end

  def show
  end

  def new
    @event = Event.find(params[:event_id])
    @rsvp = Rsvp.find(params[:rsvp_id])
    @attendee = Attendee.new
  end

  def edit
    @event = Event.find(params[:event_id])
    @rsvp = Rsvp.find(params[:event_id])
  end

  def create
    @event = Event.find(params[:event_id])
    @rsvp = Rsvp.find(params[:rsvp_id])
    @attendee = @rsvp.attendees.build(attendee_params)
    if @attendee.save
      @rsvp.adjust_total_cost
      redirect_to edit_event_rsvp_path(@event, @rsvp), notice: 'Attendee was successfully created.'
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:event_id])
    @rsvp = Rsvp.find(params[:rsvp_id])
    if @attendee.update(attendee_params)
      redirect_to edit_event_rsvp_path(@event, @rsvp), notice: 'Attendee was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:event_id])
    @rsvp = Rsvp.find(params[:rsvp_id])
    @attendee.destroy
    @rsvp.adjust_total_cost
    redirect_to edit_event_rsvp_path(@event, @rsvp), notice: 'Attendee was successfully destroyed.'
  end

  private
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    def attendee_params
      params.require(:attendee).permit(:name, :event_option_id)
    end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_form.html.erb
<%= form_for [event, rsvp, attendee] do |f| %>
  <% if attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% attendee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="attendee-form">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :event_option_id, "Options" %>
      <%= f.collection_select(:event_option_id, event.event_options, :id, :name_with_price, prompt: true, class: "form-control") %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendees/admin_index.html.erb
<h1>Attendees for <%= @event.name %> </h1>

<table class="table" id="attendees-table">
  <thead>
    <th>Name</th>
    <th>Food Option</th>
    <th>Classmate</th>
    <th>Paid?</th>
    <th>View RSVP</th>
  </thead>
  <tbody>
    <% @attendees.each do |a| %>
      <tr>
        <td><%= a.name %></td>
        <td><%= a.event_option.name %></td>
        <td><%= a.rsvp.classmate.full_name %></td>
        <td><%= a.rsvp.payment_status %></td>
        <td><%= link_to "RSVP", event_rsvp_path(a.rsvp.event_id, a.rsvp.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/attendees/edit.html.erb
<h1>Editing Attendee</h1>

<%= render 'form', attendee: @attendee, event: @event, rsvp: @rsvp %>

<%= link_to "Delete Attendee", event_rsvp_attendee_path(@event, @rsvp, @attendee), method: :delete, class: "btn btn-danger" %>
<%= link_to 'Back To RSVP', edit_event_rsvp_path(@event, @rsvp) %>

app/views/attendees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendees</h1>

<table class="table">
  <thead>
    <tr>
      <th>Rsvp</th>
      <th>Name</th>
      <th>Event option</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><%= attendee.rsvp_id %></td>
        <td><%= attendee.name %></td>
        <td><%= attendee.event_option %></td>
        <td><%= link_to 'Show', attendee %></td>
        <td><%= link_to 'Edit', edit_attendee_path(attendee) %></td>
        <td><%= link_to 'Destroy', attendee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendee', new_attendee_path %>

app/views/attendees/new.html.erb
<h1>Add Attendee for <%= @rsvp.classmate.full_name %> RSVP</h1>

<%= render 'form', attendee: @attendee, event: @event, rsvp: @rsvp %>

<%= link_to 'Back to RSVP', edit_event_rsvp_path(@event, @rsvp) %>

app/views/attendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rsvp:</strong>
  <%= @attendee.rsvp_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @attendee.name %>
</p>

<p>
  <strong>Event option:</strong>
  <%= @attendee.event_option %>
</p>

<%= link_to 'Edit', edit_attendee_path(@attendee) %> |
<%= link_to 'Back', attendees_path %>