config/routes.rb
Rails.application.routes.draw do
  resources :graduates
  root to: "pages#home"

  devise_for :classmates, prefix: 'my'

  resources :classmates

  get "/admin_dashboard", to: 'pages#admin_dashboard', as: "admin_dashboard"
  get "/admin_classmates", to: 'classmates#admin_index', as: "admin_classmates"
  get "/events/:event_id/admin_rsvps", to: 'rsvps#admin_index', as: "admin_rsvps"
  get "/events/:event_id/admin_attendees", to: 'attendees#admin_index', as: "admin_attendees"

  post "/images", to: "images#create", as: "new_image"

  post "/hook", to: 'rsvps#hook'

  resources :events do
    resources :rsvps do
      resources :attendees
    end
    resources :event_options
  end

  resources :posts

end

app/models/event.rb
class Event < ApplicationRecord

  has_many :event_options, inverse_of: :event
  has_many :rsvps, inverse_of: :event

  validates :name, presence: true
  validates :date, presence: true
  validates :content, presence: true
  validates :time, presence: true
  validates :rsvp_by, presence: true
  validates :payment_instructions, presence: true
  validates :contact_email, presence: true

  accepts_nested_attributes_for :event_options, reject_if: :all_blank

  scope :upcoming, -> { where('date >= ?', DateTime.now)}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
    authorize @events
  end

  def show
  end

  def new
    @event = Event.new
    authorize @event
    5.times { @event.event_options.build }
  end

  def edit
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @event
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :date, :content, :time, :rsvp_by, :payment_instructions, :contact_email, event_options_attributes: [:name, :price])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <br/>
  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_select :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :time %>
    <%= f.text_field :time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content, "Event Description" %>
    <%= f.text_area :content, class: "form-control", size: "100x15" %>
  </div>

  <div class="form-group">
    <p>This is the date in which guests must have their RSVP submitted</p>
    <%= f.label :rsvp_by %>
    <%= f.date_select :rsvp_by, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :payment_instructions %>
    <p>These are instructions for guests to submit alternative payment to Paypal.</p>
    <%= f.text_area :payment_instructions, class: "form-control", size: "100x10" %>
  </div>

  <div class="form-group">
    <%= f.label :contact_email %>
    <p>This is the email that classmates will use to ask questions or request changes to their rsvps</p>
    <%= f.email_field :contact_email, class: "form-control" %>
  </div>

  <h3>Event Food Options</h3>
  <p>You may have up to five event food options. You do not need to use all five options. Please leave them blank if not used.</p>

  <% if !event.persisted? %>
  <%= f.fields_for :event_options do |ff| %>
    <div class="event-option-form">
      <h4>Option</h4>
      <div class="form-group">
        <%= ff.label :name, "Description" %>
        <%= ff.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= ff.label :price, "Cost" %>
        <%= ff.number_field :price, class: "form-control", step: 0.01 %>
      </div>

      <% if ff.object.persisted? %>
        <div class="form-group">
          <%= ff.check_box :_destroy %>
          <%= ff.label :_destroy, "Delete Option" %>
        </div>
      <% end %>
    </div>
  <% end %>
  <button class="btn btn-default"><%= link_to "Add Another Event Option", "javascript:void(0)", id: "event-option-button" %></button>
  <br/>
  <% end %>

  <% if event.persisted? %>
    <% event.event_options.each do |eo| %>
      <h4>Option</h4>
      <p>Description: <%= eo.name %></p>
      <p>Price: <%= money(eo.price) %></p>
      <%= link_to "Edit Option", edit_event_event_option_path(event, eo) %>
    <% end %>
    <br/>
    <%= link_to "Add Event Option", new_event_event_option_path(event), class: "btn btn-success" %>
  <% end %>

  <div class="actions">
    <%= f.submit "Create Event", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="event-edit">
	<h3>Editing Event</h3>

	<%= render 'form', event: @event %>

	<%= link_to 'Show', @event %> |
	<%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="events-index">
  <h1>Events</h1>


  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.date %></td>
          <td><%= event.content %></td>
          <div class="btn-group" role="group" aria-label="...">
            <td>
              <% if current_classmate.admin? %>  
                <button type="button" class="btn btn-default"><%= link_to 'Show', event %></button>
              <% end %>
              <button type="button" class="btn btn-default"><%= link_to 'More Details', event %></button>
            </td>
            <td>
              <% if current_classmate.admin? %>
                <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_event_path(event) %></button>
              <% end %>  
            </td>
            <td>
              <% if current_classmate.admin? %>
                <button type="button" class="btn btn-default"><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></button>
              <% end %>
            </td>
          </div>  
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


<% if current_classmate.admin? %>
  <button class="btn btn-default"><%= link_to 'New Event', new_event_path %></button>
<% end %>
<!-- 
  <button type="button" class="btn btn-default"><%= link_to 'Create New Event', new_event_path %></button> -->
</div>

app/views/events/new.html.erb
<div class="event-new">
	<h3>New Event</h3>

	<%= render 'form', event: @event %>

	<%= link_to 'Back', events_path %>
</div>

app/views/events/show.html.erb
<div class="event-show">
  <p id="notice"><%= notice %></p>

  <h3>
    <%= @event.name %>
  </h3>

  <p>
    <strong>Date: </strong><%= @event.date %><br/>
    <%= @event.time %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= simple_format(@event.content) %>
  </p>

  <p>RSVPs must be submitted by <%= @event.rsvp_by.strftime("%m/%d/%y") %></p>

  <h4>Food Options</h4>
  <% @event.event_options.each do |option| %>
    <div>
      <p>Description: <%= option.name %></p>
      <p>Price: <%= money(option.price) %></p>
    </div>
  <% end %>

  <div>
    <% if current_classmate.rsvps.where(event_id: @event.id).empty? %>
      <button class="btn btn-default"><%= link_to 'RSVP', new_event_rsvp_path(@event) %></button>
    <% else %>
      <button class="btn btn-default"><%= link_to 'View RSVP', event_rsvp_path(@event, current_classmate.rsvps.where(event_id: @event.id)[0]) %></button>
    <% end %>
  </div>

  <button class="btn btn-default"><%= link_to 'Edit Event', edit_event_path(@event) %></button><br>
  <%= link_to 'Back', events_path %>
</div>