config/routes.rb
Rails.application.routes.draw do
  resources :graduates
  root to: "pages#home"

  devise_for :classmates, prefix: 'my'

  resources :classmates

  get "/admin_dashboard", to: 'pages#admin_dashboard', as: "admin_dashboard"
  get "/admin_classmates", to: 'classmates#admin_index', as: "admin_classmates"
  get "/events/:event_id/admin_rsvps", to: 'rsvps#admin_index', as: "admin_rsvps"
  get "/events/:event_id/admin_attendees", to: 'attendees#admin_index', as: "admin_attendees"

  post "/images", to: "images#create", as: "new_image"

  post "/hook", to: 'rsvps#hook'

  resources :events do
    resources :rsvps do
      resources :attendees
    end
    resources :event_options
  end

  resources :posts

end

app/models/rsvp.rb
class Rsvp < ApplicationRecord

  has_many    :attendees, inverse_of: :rsvp
  belongs_to  :event, optional: true
  belongs_to  :classmate

  validates :classmate_id, presence: true

  accepts_nested_attributes_for :attendees, reject_if: :all_blank, allow_destroy: true

  after_create :compute_total_cost

  def adjust_total_cost
    original_cost = self.total_cost
    new_cost = 0
    self.attendees.each do |a|
      new_cost += a.price
    end
    if new_cost < original_cost && self.payment_status != "Not Paid"
      self.update(payment_status: "Over Paid", total_cost: new_cost)
    elsif new_cost > original_cost && self.payment_status != "Not Paid"
      self.update(payment_status: "Extra Payment Due", total_cost: new_cost)
    elsif self.payment_status == "Not Paid"
      self.update(total_cost: new_cost)
    end
  end

  private

  def compute_total_cost
    total_cost = 0
    self.attendees.each do |a|
      total_cost += a.price
    end
    self.total_cost = total_cost
    self.save
  end

end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]

    protect_from_forgery except: [:hook]

  def index
    @rsvps = Rsvp.all
    authorize @rsvps
    @event = Event.find(params[:event_id])
  end

  def admin_index
    @event = Event.find(params[:event_id])
    @rsvps = @event.rsvps.includes(:attendees)
  end

  def show
    paypal_url_service = PaypalUrlCreator.new(@rsvp)
    @paypal_url = paypal_url_service.call(event_rsvp_path(@event, @rsvp))
  end

  def new
    @rsvp = Rsvp.new(event_id: params[:event_id])
    authorize @rsvp
    @event = Event.find(params[:event_id])
    @classmate_attendee = @rsvp.attendees.build(name: current_classmate.full_name)
    7.times { @rsvp.attendees.build }
  end

  def edit
  end

  def create
    @rsvp = Rsvp.new(rsvp_params)
    if params[:administrator] == "1"
      @rsvp.classmate_id = 1
    end
    @event = Event.find(params[:event_id])
    if @rsvp.save
      redirect_to event_rsvp_path(@event, @rsvp), notice: 'Rsvp was successfully created.'
    else
      render :new
    end
  end

  def update
    if @rsvp.update(rsvp_params)
      redirect_to event_rsvp_path(@rsvp.event_id, @rsvp.id), notice: 'Rsvp was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(@rsvp.event_id)
    @rsvp.destroy
    redirect_to event_path(@event), notice: 'Rsvp was successfully destroyed.'
  end

  def hook
    @rsvp = Rsvp.find(params[:item_number])
    PayRsvp.new(params, "paypal", @rsvp).call
    render nothing: true
  end

  private
    def set_rsvp
      @rsvp = Rsvp.includes(attendees: :event_option).find(params[:id])
      @event = Event.find(params[:event_id])
    end

    def rsvp_params
      params.require(:rsvp).permit(:classmate_id, :total_cost, :event_id, :payment_status, :paid_amount, attendees_attributes: [:id, :name, :event_option_id, :rsvp_id])
    end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper

  def total_amount_paid(rsvp)
    rsvp.paid_amount.nil? ? 0 : rsvp.paid_amount
  end

end

app/views/rsvps/_form.html.erb
<%= form_for [event, rsvp] do |f| %>
  <% if rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>

      <ul>
      <% rsvp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Check this box if you are an administrator creating an rsvp for another classmate who is not a user of the website. If the user has already paid please fill out the section below to apply the appropriate payment status.</p>
  <%= check_box_tag :administrator %>
  <%= label_tag :administrator, "Administrator" %>

  <%= f.hidden_field :classmate_id, value: "#{current_classmate.id}" %>
  <%= f.hidden_field :event_id, value: "#{event.id}" %>

  <% if !rsvp.persisted? %>
    <%= f.fields_for :attendees do |ff| %>
      <div class="attendee-form">
        <div class="form-group">
          <%= ff.label :name %>
          <%= ff.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= ff.label :event_option_id, "Options" %>
          <%= ff.collection_select(:event_option_id, @event.event_options, :id, :name_with_price, prompt: true, class: "form-control") %>
        </div>
      </div>
    <% end %>

    <%= link_to "Add Attendee", "javascript:void(0)", id: "add-attendee-button"%>
  <% end %>

  <% if rsvp.persisted? %>
    <% rsvp.attendees.each do |a| %>
      <div>
        <h4>
          <%= a.name %>
          <small>
          <%=a.event_option.name%> <%=money(a.event_option.price) %>
          <%=link_to "Edit", edit_event_rsvp_attendee_path(event, rsvp, a) %>
          </small>
        </h4>

      </div>
    <% end %>

    <%= link_to "Add Attendee", new_event_rsvp_attendee_path(event, rsvp), class: "btn btn-primary" %>

  <% end %>

  <% if current_classmate.admin? %>
    <div class="card">
      <div class="form-group">
        <h4>Viewable to Administrators only.</h4>
        <%= f.label :payment_status %>
        <%= f.select(:payment_status, options_for_select(["Not Paid", "Paid", "Extra Payment Due", "Over Paid"], rsvp.payment_status)) %>
      </div>

      <p>Total Cost: <strong><%= money(rsvp.total_cost) %></strong></p>

      <div class="form-group">
        <%= f.label :paid_amount, "Amount Paid" %>
        <%= f.number_field :paid_amount, value: total_amount_paid(rsvp), class: "form-control", step: 0.01 %>
      </div>
      <p>If changes to an rsvp where made and a refund was made or the classmate made an additional payment please input the total amount the classmate paid here.</p>
    </div>
  <% end %>




  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/rsvps/admin_index.html.erb
<h1>RSVPs for <%= @event.name %> <%=@event.date.strftime("%m/%d/%y") %></h1>

<table class="table">
  <thead>
    <th>ID</th>
    <th>Classmate</th>
    <th>Total Cost</th>
    <th>Amount Paid</th>
    <th>Payment Status</th>
    <th>Payment Date</th>
  </thead>
  <tbody>
    <% @rsvps.each do |rsvp| %>
      <tr>
        <td><%= rsvp.id %></td>
        <td><%= link_to rsvp.classmate.full_name, event_rsvp_path(rsvp.event_id, rsvp.id) %></td>
        <td><%= money(rsvp.total_cost) %></td>
        <td><%= rsvp.paid_amount.nil? ? "--" : money(rsvp.paid_amount) %>
        <td><%= rsvp.payment_status %></td>
        <td><%= rsvp.payment_on ? rsvp.payment_on.strftime("%m/%d/%y") : "--" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rsvps/edit.html.erb
<div class="rsvp-edit">
	<h1>Editing Rsvp</h1>

	<%= render 'form', rsvp: @rsvp, event: @event %>


	<%= link_to 'Back', event_rsvp_path(@event, @rsvp) %>
</div>

app/views/rsvps/index.html.erb
<div class="rsvp-index">
  <p id="notice"><%= notice %></p>

  <h3>RSVPs</h3>

  <table class="table">
    <thead>
      <tr>
        <th>Classmate</th>
        <th>Total cost</th>
        <th>Payment status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @rsvps.each do |rsvp| %>
        <tr>
          <td><%= rsvp.classmate.full_name %></td>
          <td><%= money(rsvp.total_cost) %></td>
          <td><%= rsvp.payment_status %></td>
          <td><button class="btn btn-default"><%= link_to 'Show', event_rsvp_path(rsvp.event_id, rsvp.id) %></button></td>
          <td><button class="btn btn-default"><%= link_to 'Edit', edit_event_rsvp_path(rsvp.event_id, rsvp.id) %></button></td>
          <td><button class="btn btn-default"><%= link_to 'Destroy', event_rsvp_path(rsvp.event_id, rsvp.id), method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <button class="btn btn-default"><%= link_to 'New Rsvp', new_event_rsvp_path(@event) %></button>
</div>

app/views/rsvps/new.html.erb
<div class="rsvp-new">
	<h3>New Rsvp</h3>

	<%= render 'form', rsvp: @rsvp, event: @event %>

	<%= link_to 'Back', event_rsvps_path(@event) %>
</div>

app/views/rsvps/show.html.erb
<div class="rsvp-show">
	<p id="notice"><%= notice %></p>

	<h2>RSVP for: <%= @event.name %></h3>
	<h4>Date: <%= @event.date.strftime("%m/%d/%y")%></h4>

	<h2>Attending:</h2>
	<% @rsvp.attendees.each do |a| %>
	  <div>
	    <p><%= a.name %></p>
	    <p>Selected Option: <%= a.event_option.name%></p>
	    <p>Cost: <%= money(a.event_option.price) %></p>
	  </div>
	<% end %>

	<h3>Total Cost: <%= money(@rsvp.total_cost)%></h3>



	<%= link_to image_tag("https://www.paypalobjects.com/webstatic/en_US/i/buttons/checkout-logo-small.png"), @paypal_url %>
	
	<p>If paying by check or cash please send payment to the following:<br/>
	  <%= simple_format(@event.payment_instructions) %>
	</p>

	<button class="btn btn-default"><%= link_to 'Edit', edit_event_rsvp_path(@event, @rsvp) %></button><br>
	<%= link_to 'Back', event_rsvps_path(@event) %>
</div>