config/routes.rb
Rails.application.routes.draw do
  resources :graduates
  root to: "pages#home"

  devise_for :classmates, prefix: 'my'

  resources :classmates

  get "/admin_dashboard", to: 'pages#admin_dashboard', as: "admin_dashboard"
  get "/admin_classmates", to: 'classmates#admin_index', as: "admin_classmates"
  get "/events/:event_id/admin_rsvps", to: 'rsvps#admin_index', as: "admin_rsvps"
  get "/events/:event_id/admin_attendees", to: 'attendees#admin_index', as: "admin_attendees"

  post "/images", to: "images#create", as: "new_image"

  post "/hook", to: 'rsvps#hook'

  resources :events do
    resources :rsvps do
      resources :attendees
    end
    resources :event_options
  end

  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord

  belongs_to :rsvp
  belongs_to :event_option


  validates :name, presence: true
  validates :event_option_id, presence: true
  #validates :rsvp_id, presence:true

  delegate :price, to: :event_option

end

app/models/classmate.rb
class Classmate < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :rsvps

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/event.rb
class Event < ApplicationRecord

  has_many :event_options, inverse_of: :event
  has_many :rsvps, inverse_of: :event

  validates :name, presence: true
  validates :date, presence: true
  validates :content, presence: true
  validates :time, presence: true
  validates :rsvp_by, presence: true
  validates :payment_instructions, presence: true
  validates :contact_email, presence: true

  accepts_nested_attributes_for :event_options, reject_if: :all_blank

  scope :upcoming, -> { where('date >= ?', DateTime.now)}
end

app/models/event_option.rb
class EventOption < ApplicationRecord

  has_many    :attendees
  belongs_to  :event

  validates :name, presence: true
  validates :price, presence: true


  def name_with_price
    "#{self.name}: $#{self.price}"
  end



end

app/models/graduate.rb
class Graduate < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :classmate

  delegate :full_name, to: :classmate, prefix: true
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord

  has_many    :attendees, inverse_of: :rsvp
  belongs_to  :event, optional: true
  belongs_to  :classmate

  validates :classmate_id, presence: true

  accepts_nested_attributes_for :attendees, reject_if: :all_blank, allow_destroy: true

  after_create :compute_total_cost

  def adjust_total_cost
    original_cost = self.total_cost
    new_cost = 0
    self.attendees.each do |a|
      new_cost += a.price
    end
    if new_cost < original_cost && self.payment_status != "Not Paid"
      self.update(payment_status: "Over Paid", total_cost: new_cost)
    elsif new_cost > original_cost && self.payment_status != "Not Paid"
      self.update(payment_status: "Extra Payment Due", total_cost: new_cost)
    elsif self.payment_status == "Not Paid"
      self.update(total_cost: new_cost)
    end
  end

  private

  def compute_total_cost
    total_cost = 0
    self.attendees.each do |a|
      total_cost += a.price
    end
    self.total_cost = total_cost
    self.save
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :authenticate_classmate!

  def home
    @posts = Post.all.order('created_at DESC')
    @events = Event.upcoming
  end

  def admin_dashboard
    @events = Event.all.order('date DESC')
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_classmate!

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    authorize @post
    if @post.save
      redirect_to post_path(@post)
    else
      flash.now[:alert] = "Your post was not saved"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
      redirect_to post_path(@post), notice: "Post Updated Successfully"
    else
      flash.now[:alert] = "Post changes not saved"
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    authorize @post
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post
    @post.destroy
    redirect_to root_path, notice: "Post successfully deleted"
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :classmate_id)
  end

end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]

    protect_from_forgery except: [:hook]

  def index
    @rsvps = Rsvp.all
    authorize @rsvps
    @event = Event.find(params[:event_id])
  end

  def admin_index
    @event = Event.find(params[:event_id])
    @rsvps = @event.rsvps.includes(:attendees)
  end

  def show
    paypal_url_service = PaypalUrlCreator.new(@rsvp)
    @paypal_url = paypal_url_service.call(event_rsvp_path(@event, @rsvp))
  end

  def new
    @rsvp = Rsvp.new(event_id: params[:event_id])
    authorize @rsvp
    @event = Event.find(params[:event_id])
    @classmate_attendee = @rsvp.attendees.build(name: current_classmate.full_name)
    7.times { @rsvp.attendees.build }
  end

  def edit
  end

  def create
    @rsvp = Rsvp.new(rsvp_params)
    if params[:administrator] == "1"
      @rsvp.classmate_id = 1
    end
    @event = Event.find(params[:event_id])
    if @rsvp.save
      redirect_to event_rsvp_path(@event, @rsvp), notice: 'Rsvp was successfully created.'
    else
      render :new
    end
  end

  def update
    if @rsvp.update(rsvp_params)
      redirect_to event_rsvp_path(@rsvp.event_id, @rsvp.id), notice: 'Rsvp was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(@rsvp.event_id)
    @rsvp.destroy
    redirect_to event_path(@event), notice: 'Rsvp was successfully destroyed.'
  end

  def hook
    @rsvp = Rsvp.find(params[:item_number])
    PayRsvp.new(params, "paypal", @rsvp).call
    render nothing: true
  end

  private
    def set_rsvp
      @rsvp = Rsvp.includes(attendees: :event_option).find(params[:id])
      @event = Event.find(params[:event_id])
    end

    def rsvp_params
      params.require(:rsvp).permit(:classmate_id, :total_cost, :event_id, :payment_status, :paid_amount, attendees_attributes: [:id, :name, :event_option_id, :rsvp_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def class_years
    this_year = Time.now.year
    classes = []
    classes << this_year
    100.times do |i|
      classes << (this_year - 1)
      this_year -= 1
    end
    classes
  end

  def money price
    "$#{number_with_precision(price, precision: 2)}"
  end

  def show_main_nav?
    !(controller_name == 'sessions') && !(current_page?(new_classmate_registration_path))
  end

end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/classmates_helper.rb
module ClassmatesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/graduates_helper.rb
module GraduatesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper

  def total_amount_paid(rsvp)
    rsvp.paid_amount.nil? ? 0 : rsvp.paid_amount
  end

end

app/views/layouts/_flash_messages.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <button class="close" data-dismiss="alert">x</button>
    <%= flash[:alert] %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-info">
    <button class="close" data-dismiss="alert">x</button>
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-trans navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsible">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand text-danger" href="/">Palmyra Bennet Alumni</a>
    </div>
    <div class="navbar-collapse collapse" id="navbar-collapsible">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Classmates", classmates_path %></li>
        <li><%= link_to "Events", events_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to current_classmate.full_name, edit_classmate_registration_path(current_classmate) %></li>
        
        <% if current_classmate.admin? %>
          <li><%= link_to "Admin", admin_dashboard_path %>
        <% end %>
        <% if current_classmate %>
          <li><%= link_to "Logout", destroy_classmate_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PalmyraBennetAlumni</title>
    <!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs-3.3.6/jq-2.2.3/dt-1.10.12/af-2.1.2/b-1.2.1/b-colvis-1.2.1/b-print-1.2.1/r-2.1.0/datatables.min.css"/> -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jq-2.2.4/dt-1.10.13/b-1.2.4/b-html5-1.2.4/r-2.1.0/datatables.min.css"/>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.6/jq-2.2.3/dt-1.10.12/af-2.1.2/b-1.2.1/b-colvis-1.2.1/b-print-1.2.1/r-2.1.0/datatables.min.js"></script> -->

    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/jq-2.2.4/dt-1.10.13/b-1.2.4/b-html5-1.2.4/r-2.1.0/datatables.min.js"></script>

    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>







  </head>

  <body>

    <% if show_main_nav? %>
      <%= render "layouts/navbar" %>
    <% end %>

    <div class="container">
        <div class="row">
          <div class="col-sm-1"></div>
          <div class="alerts col-sm-10">
            <%= render "layouts/flash_messages" %>
          </div>
          <div class="col-sm-1"></div>
        </div>
        <%= yield %>
    </div>
  </body>
</html>

app/views/pages/admin_dashboard.html.erb
<div class="admin-dash">
  <h1>Admin Dashboard</h1>

  <button class="btn btn-default"><%= link_to "All Classmates", admin_classmates_path %></button><button class="btn btn-default"><%= link_to "Manage Graduate Lists", graduates_path %></button>

  <h4>Events</h4>
  <table class="table">
    <thead>
      <th>Event</th>
      <th>Date</th>
      <th>View RSVPS</th>
      <th>View Attendees</th>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= link_to event.name, event_path(event) %></td>
          <td><%= event.date.strftime("%m/%d/%y") %></td>
          <td><button class="btn btn-default"><%= link_to "See RSVPs", admin_rsvps_path(event.id) %></button></td>
          <td><button class="btn btn-default"><%= link_to "See Attendees", admin_attendees_path(event.id) %></button></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pages/home.html.erb
<div class="home-page">
  <div class="row">
    <div class="col-md-5">
      <div class="home-panel" id="posts">  
        <h3>Posts</h3>
        <button class="btn btn-default"><%= link_to "Create new post", new_post_path %></button>
        <% @posts.each do |post| %>
          <div class="card card-event">
            <h3><%= post.title %></h3>
            <p><%=simple_format(post.content) %></p>
            <%= link_to "Read More", post_path(post) %>
          </div>
        <% end %>
      </div>
    </div>  
    <div class="col-md-5">
      <div class="home-panel" id="events">
        <h3>Upcoming Events</h3>

        <% if @events.empty? %>
          <h5>No events to show</h5>
        <% else %>
          <% @events.each do |event| %>

            <div class="card card-event">
              <h3><%= link_to event.name, event_path(event) %></h3>
              <p>Date: <%= event.date.strftime("%m/%d/%y") %></p>
              <p><%= simple_format(event.content) %></p>
              <button class="btn btn-default"><%= link_to "See more and RSVP", event_path(event)%></button>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>